// ============================================================
// DATA PORTOFOLIO — Edit file ini untuk update konten website
// ============================================================

export const siteConfig = {
  name: "Bicara Digital",
  owner: "Bagoes Tri Anggoro",
  tagline: "Tech & Creative — Web, AI, and Brand",
  description:
    "I build digital products that work — from business systems and web apps to AI automation and brand design. Based in Semarang, working globally.",
  location: "Semarang, Indonesia",
  email: "hello@bicaradigital.com", // ganti dengan email aktif
  whatsapp: "+6282133467984",
  github: "https://github.com/bicaradigital",
  domain: "bicaradigital.com",
  availableForWork: true,
}

// ============================================================
// SERVICES
// ============================================================
export const services = [
  {
    id: "web-dev",
    icon: "⚡",
    title: "Web Development",
    titleId: "Pengembangan Web",
    desc: "Modern, fast, and responsive web apps — from landing pages to full-stack SaaS platforms built for real business needs.",
    descId: "Aplikasi web modern, cepat, dan responsif — dari landing page hingga platform SaaS full-stack.",
    tags: ["Next.js", "PHP", "Tailwind", "TypeScript", "Vercel"],
  },
  {
    id: "ai-automation",
    icon: "🧠",
    title: "AI & Automation",
    titleId: "AI & Otomasi",
    desc: "Integrate AI into your workflow — intelligent tools, chatbots, and automated systems using GPT, Claude, and Gemini.",
    descId: "Integrasikan AI ke alur kerja bisnismu — chatbot, tools otomatis, dan sistem cerdas.",
    tags: ["Python", "Claude API", "GPT", "Streamlit", "Automation"],
  },
  {
    id: "business-system",
    icon: "📊",
    title: "Business Systems",
    titleId: "Sistem Bisnis",
    desc: "Custom ERP and operational tools — finance, inventory, kost management, and HPP calculators tailored for SMEs.",
    descId: "Sistem ERP dan tools operasional — keuangan, inventori, dan manajemen bisnis untuk UMKM.",
    tags: ["Dashboard", "PostgreSQL", "Supabase", "Export PDF"],
  },
  {
    id: "brand-design",
    icon: "🎨",
    title: "Brand & Logo Design",
    titleId: "Desain Brand & Logo",
    desc: "5+ years crafting brand identities — logos, packaging, visual systems, and marketing materials that leave an impression.",
    descId: "5+ tahun merancang identitas brand — logo, kemasan, sistem visual, dan materi marketing.",
    tags: ["Figma", "Canva", "Logo", "Packaging", "Brand Identity"],
  },
  {
    id: "email-marketing",
    icon: "✉️",
    title: "Email Marketing",
    titleId: "Email Marketing",
    desc: "Strategy, copywriting, and campaign automation. Build and nurture your audience with high-converting email flows.",
    descId: "Strategi, copywriting, dan otomasi kampanye email yang mengkonversi.",
    tags: ["MailerLite", "Automation", "Copywriting", "Campaign"],
  },
  {
    id: "saas-dev",
    icon: "🚀",
    title: "SaaS Development",
    titleId: "Pengembangan SaaS",
    desc: "End-to-end SaaS product development — MVP to scalable multi-user platforms with auth, billing, and export features.",
    descId: "Pengembangan produk SaaS end-to-end — dari MVP hingga platform multi-user yang scalable.",
    tags: ["Next.js", "ShadCN", "TypeScript", "Multi-user", "Auth"],
  },
]

// ============================================================
// PROJECTS — Dev & System
// ============================================================
export const devProjects = [
  {
    id: "ami-food",
    category: "Web Dev",
    year: "2024",
    title: "Ami Food — Website Profile",
    client: "Ami Food, Semarang (F&B)",
    desc: "Modern landing page for an authentic Semarang culinary business established in 1997. Features menu showcase, catering service info, testimonials, and brand identity.",
    descId: "Landing page modern untuk usaha kuliner autentik Semarang sejak 1997.",
    stack: ["Next.js 16", "React 19", "Tailwind CSS 4", "TypeScript", "shadcn/ui", "Vercel"],
    type: "web",
    highlight: "Responsive, SEO-ready, dark/light mode",
  },
  {
    id: "keuangan-pintar",
    category: "Business System",
    year: "2024",
    title: "KeuanganPintar Pro",
    client: "Bicara Digital (SaaS)",
    desc: "Personal finance dashboard — real-time income, expense, savings tracking with Supabase auth, transaction CRUD, and monthly report generation.",
    descId: "Dashboard keuangan personal real-time dengan autentikasi Supabase dan laporan bulanan.",
    stack: ["Next.js 14", "Supabase", "ShadCN", "Tailwind", "Lucide", "Vercel"],
    type: "business",
    highlight: "Full auth system + real-time stats",
  },
  {
    id: "buku-saku",
    category: "Business System",
    year: "2024",
    title: "Buku Saku Keuangan Usaha",
    client: "UMKM Resep Mom",
    desc: "Lightweight web-based financial bookkeeping for SMEs — no install required, multi-user, auto-save, export PDF/Excel, and profit/loss reports by period.",
    descId: "Pembukuan keuangan digital ringan untuk UMKM — multi-user, export PDF/Excel, laporan laba rugi.",
    stack: ["Next.js", "TypeScript", "localStorage", "shadcn/ui", "Tailwind"],
    type: "business",
    highlight: "Multi-user + export PDF & Excel",
  },
  {
    id: "kost-management",
    category: "Business System",
    year: "2025",
    title: "Management Pengelola Kost",
    client: "Property Management SaaS",
    desc: "Digital kost management system — room & tenant data, billing, auto due-date notifications, occupancy dashboard, and financial reports with PDF/Excel export.",
    descId: "Sistem manajemen kost digital — data kamar, penyewa, tagihan, dan notifikasi jatuh tempo otomatis.",
    stack: ["Next.js", "PostgreSQL", "TypeScript", "shadcn/ui", "Vercel"],
    type: "business",
    highlight: "Auto notifications + full financial reports",
  },
  {
    id: "hpp-retort",
    category: "AI / Automation",
    year: "2024",
    title: "Tools HPP Jasa Retort — R2B",
    client: "PT Rumah Retort Bersama",
    desc: "Streamlit app for automated retort service HPP calculation — dynamic packaging input, auto cost computation (water, gas, electricity, tax, margin), CSV & PDF export.",
    descId: "Kalkulator HPP jasa retort otomatis — input dinamis kemasan, ekspor CSV & PDF.",
    stack: ["Python", "Streamlit", "PDF Export", "CSV", "Login System"],
    type: "ai",
    highlight: "Automated cost calculation engine",
  },
  {
    id: "retort-f0",
    category: "AI / Automation",
    year: "2024",
    title: "Tools Retort R2B — F₀ Calculator",
    client: "PT Rumah Retort Bersama",
    desc: "Retort process recording app with automatic F₀ value calculation — per-minute temp & pressure input, PDF reports with watermark, multi-user login system.",
    descId: "Pencatatan proses retort dengan kalkulasi nilai F₀ otomatis dan laporan PDF berlogo.",
    stack: ["Python", "Streamlit", "F₀ Algorithm", "PDF Report", "Multi-user"],
    type: "ai",
    highlight: "Scientific F₀ algorithm implementation",
  },
  {
  id: "dashboard-r2b",
  category: "Business System",
  year: "2024",
  title: "Dashboard Keuangan R2B",
  client: "PT Rumah Retort Bersama",
  desc: "Internal financial management dashboard for PT Rumah Retort Bersama — real-time transaction recording, profit/loss reports, interactive charts, period filtering, and bulk import/export via PDF & Excel.",
  stack: ["Next.js", "Supabase", "TypeScript", "shadcn/ui", "Tailwind CSS"],
  type: "business",
  highlight: "Real-time financial dashboard · Export PDF & Excel",
  githubUrl: null,
  liveUrl: null,
  },
  {
    id: "hpp-umkm",
    category: "Business System",
    year: "2024",
    title: "Kalkulator HPP UMKM",
    client: "Open Tool — UMKM Indonesia",
    desc: "Web-based HPP calculator for Indonesian SMEs — multi-product, real-time calculation of HPP, selling price, gross profit, 0.5% UMKM tax, and net profit. Auto-save + CSV/PDF export.",
    descId: "Kalkulator HPP web untuk UMKM — kalkulasi real-time, pajak 0.5%, export CSV/PDF.",
    stack: ["Next.js", "TypeScript", "react-to-print", "localStorage", "shadcn/ui"],
    type: "business",
    highlight: "UMKM tax calculation built-in",
  },
  {
    id: "portfolio-generator",
    category: "AI / Automation",
    year: "2025",
    title: "Portfolio Generator — AI Powered",
    client: "Bicara Digital (SaaS Tool)",
    desc: "AI-powered portfolio builder — fill a form, pick a template, get real-time preview, and export to PDF. Uses Anthropic Claude API for auto-generating professional descriptions.",
    descId: "Generator portofolio bertenaga AI — isi form, pilih template, export PDF otomatis.",
    stack: ["Next.js 16", "Claude API", "React 19", "shadcn/ui", "TypeScript"],
    type: "ai",
    highlight: "Claude API integration for AI copy",
  },
]

// ============================================================
// DESIGN PROJECTS — Ganti src dengan path gambar aslimu
// ============================================================
export const designProjects = [
  // --- LOGO DESIGN ---
  {
    id: "logo-1",
    category: "logo",
    categoryLabel: "Logo Design",
    title: "Brand Identity — Project 1",
    client: "Client Name", // ganti
    year: "2024",
    desc: "Full logo design and brand identity system.",
    // Ganti src dengan path gambar: "/images/logo/logo-1.jpg"
    // atau link Canva/Drive/Behance
    src: null,
    canvaLink: null, // isi link Canva jika ada
  },
  {
    id: "logo-2",
    category: "logo",
    categoryLabel: "Logo Design",
    title: "Brand Identity — Project 2",
    client: "Client Name",
    year: "2024",
    desc: "Logo design with typography and color system.",
    src: null,
    canvaLink: null,
  },
  {
    id: "logo-3",
    category: "logo",
    categoryLabel: "Logo Design",
    title: "Brand Identity — Project 3",
    client: "Client Name",
    year: "2023",
    desc: "Minimalist logo design for a local business.",
    src: null,
    canvaLink: null,
  },
  {
    id: "logo-4",
    category: "logo",
    categoryLabel: "Logo Design",
    title: "Brand Identity — Project 4",
    client: "Client Name",
    year: "2023",
    desc: "Modern logo with brand guidelines.",
    src: null,
    canvaLink: null,
  },
  {
    id: "logo-5",
    category: "logo",
    categoryLabel: "Logo Design",
    title: "Brand Identity — Project 5",
    client: "Client Name",
    year: "2022",
    desc: "Custom logo design for product brand.",
    src: null,
    canvaLink: null,
  },
  // --- PACKAGING ---
  {
    id: "pkg-1",
    category: "packaging",
    categoryLabel: "Packaging",
    title: "Packaging Design — Product 1",
    client: "Client Name",
    year: "2024",
    desc: "Full packaging design with print-ready files.",
    src: null,
    canvaLink: null,
  },
  {
    id: "pkg-2",
    category: "packaging",
    categoryLabel: "Packaging",
    title: "Packaging Design — Product 2",
    client: "Client Name",
    year: "2024",
    desc: "Label and box packaging for food product.",
    src: null,
    canvaLink: null,
  },
  {
    id: "pkg-3",
    category: "packaging",
    categoryLabel: "Packaging",
    title: "Packaging Design — Product 3",
    client: "Client Name",
    year: "2023",
    desc: "Premium packaging with brand elements.",
    src: null,
    canvaLink: null,
  },
  {
    id: "pkg-4",
    category: "packaging",
    categoryLabel: "Packaging",
    title: "Packaging Design — Product 4",
    client: "Client Name",
    year: "2023",
    desc: "Flexible packaging for UMKM product.",
    src: null,
    canvaLink: null,
  },
  {
    id: "pkg-5",
    category: "packaging",
    categoryLabel: "Packaging",
    title: "Packaging Design — Product 5",
    client: "Client Name",
    year: "2022",
    desc: "Sticker label and sachet design.",
    src: null,
    canvaLink: null,
  },
  // --- KAOS / APPAREL ---
  {
    id: "kaos-1",
    category: "apparel",
    categoryLabel: "Apparel Design",
    title: "T-Shirt Design — Collection 1",
    client: "Client Name",
    year: "2024",
    desc: "Custom apparel graphic for clothing brand.",
    src: null,
    canvaLink: null,
  },
  {
    id: "kaos-2",
    category: "apparel",
    categoryLabel: "Apparel Design",
    title: "T-Shirt Design — Collection 2",
    client: "Client Name",
    year: "2024",
    desc: "Screen print design for event merchandise.",
    src: null,
    canvaLink: null,
  },
  {
    id: "kaos-3",
    category: "apparel",
    categoryLabel: "Apparel Design",
    title: "T-Shirt Design — Collection 3",
    client: "Client Name",
    year: "2023",
    desc: "Streetwear style graphic design.",
    src: null,
    canvaLink: null,
  },
  {
    id: "kaos-4",
    category: "apparel",
    categoryLabel: "Apparel Design",
    title: "T-Shirt Design — Collection 4",
    client: "Client Name",
    year: "2023",
    desc: "Community event apparel design.",
    src: null,
    canvaLink: null,
  },
  {
    id: "kaos-5",
    category: "apparel",
    categoryLabel: "Apparel Design",
    title: "T-Shirt Design — Collection 5",
    client: "Client Name",
    year: "2022",
    desc: "Typography-based apparel illustration.",
    src: null,
    canvaLink: null,
  },
]

// ============================================================
// SKILLS
// ============================================================
export const skillGroups = [
  {
    group: "Frontend & Web",
    skills: ["Next.js", "React", "TypeScript", "Tailwind CSS", "PHP", "shadcn/ui"],
  },
  {
    group: "AI & Automation",
    skills: ["Python", "Streamlit", "Claude API", "GPT-4", "Gemini", "Automation"],
  },
  {
    group: "No-Code & Deployment",
    skills: ["Wix", "Carrd", "v0.dev", "Vercel", "GitHub"],
  },
  {
    group: "Design",
    skills: ["Figma", "Canva", "Logo Design", "Brand Identity", "Packaging"],
  },
  {
    group: "Marketing & Productivity",
    skills: ["MailerLite", "Email Marketing", "Google Workspace", "MS Office"],
  },
  {
    group: "Database & Backend",
    skills: ["Supabase", "PostgreSQL", "localStorage", "REST API"],
  },
]
